
const mongoose = require("mongoose");
const inventory = mongoose.Schema({
  id: Number,
  item: Array
})
module.exports = mongoose.model("inventory", inventory)
/*,
LiteCase: {name: String,
    cnt: Number},
  GoldCase:  {name: String,
    cnt: Number},
  PerfectCase:  {name: String,
    cnt: Number},
  RubyCase:  {name: String,
    cnt: Number},
  RoomOne:  {name: String,
    cnt: Number},
  RoomTwo:  {name: String,
    cnt: Number},
  RoomThree:  {name: String,
    cnt: Number},
  Start:  {name: String,
    cnt: Number},
  Lite:  {name: String,
    cnt: Number},
  Medium:  {name: String,
    cnt: Number},
  Iron:  {name: String,
    cnt: Number},
  Gold:  {name: String,
    cnt: Number},
  Platinum:  {name: String,
    cnt: Number},
  Wolfram:  {name: String,
    cnt: Number},
  Premium:  {name: String,
    cnt: Number},
  Vital:  {name: String,
    cnt: Number},
  Lord:  {name: String,
    cnt: Number},
  Benefactor:  {name: String,
    cnt: Number},
  Sponsor:  {name: String,
    cnt: Number},
  Shop:  {name: String,
    cnt: Number}*/